# Generated by rust2rpm 26
%bcond_without check

# prevent library files from being installed
%global cargo_install_lib 0

%global crate container-desktop-entries

%global ver ###
%global commit ###
%global date ###

Name:           container-desktop-entries-client
Version:        %{ver}~%{date}
Release:        %autorelease
Summary:        The client tool to send desktop entries to a host system. Only needs to be installed in containers

SourceLicense:  Apache-2.0
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

URL:            https://github.com/ryanabx/container-desktop-entries
Source:         container-desktop-entries-client-%{ver}.tar.xz
Source:         container-desktop-entries-client-%{ver}-vendor.tar.xz

BuildRequires:  cargo-rpm-macros >= 26
BuildRequires:  rustc
BuildRequires:  cargo
BuildRequires:  just

%global _description %{expand:
%{summary}.}

%description %{_description}

%prep
%autosetup -n %{crate}-%{ver} -p1 -a1
%cargo_prep -N
cat .vendor/config.toml >> .cargo/config

%build
cargo build --release --frozen --offline --no-default-features
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
install -Dm0755 target/release/container-desktop-entries %{buildroot}/%{_bindir}/container-desktop-entries-client

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
# %%license cargo-vendor.txt
%doc README.md
%{_bindir}/%{name}

%changelog
%autochangelog
