//! # D-Bus interface proxy for: `net.ryanabx.DesktopEntry`
//!
//! This code was generated by `zbus-xmlgen` `4.1.0` from D-Bus introspection data.
//! Source: `net.ryanabx.DesktopEntry.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::PropertiesProxy`]
//! * [`zbus::fdo::PeerProxy`]
//! * [`zbus::fdo::IntrospectableProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
    interface = "net.ryanabx.DesktopEntry",
    default_path = "/net/ryanabx/DesktopEntry",
    assume_defaults = true
)]
trait DesktopEntry {
    /// RegisterChangeHandler method
    fn register_change_handler(&self) -> zbus::Result<()>;

    /// RegisterEntry method
    fn register_entry(&self, appid: &str, entry: &str) -> zbus::Result<()>;

    /// RegisterIcon method
    fn register_icon(&self, name: &str, data: &[u8]) -> zbus::Result<()>;

    /// EntryChanged signal
    #[zbus(signal)]
    fn entry_changed(&self, appid: &str) -> zbus::Result<()>;

    /// IconChanged signal
    #[zbus(signal)]
    fn icon_changed(&self, icon_name: &str) -> zbus::Result<()>;
}
