//! # D-Bus interface proxy for: `net.ryanabx.DesktopEntry`
//!
//! This code was generated by `zbus-xmlgen` `4.1.0` from D-Bus introspection data.
//! Source: `net.ryanabx.DesktopEntry.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::IntrospectableProxy`]
//! * [`zbus::fdo::PropertiesProxy`]
//! * [`zbus::fdo::PeerProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
    interface = "net.ryanabx.DesktopEntry",
    default_path = "/net/ryanabx/DesktopEntry",
    assume_defaults = true
)]
trait DesktopEntry {
    /// RegisterEntries method
    fn register_entries(&self, entry_paths: &[&str]) -> zbus::Result<Vec<String>>;

    /// RegisterIcons method
    fn register_icons(&self, icon_paths: &[&str], subpaths: &[&str]) -> zbus::Result<Vec<String>>;
}
